### ISSUE TITLE
environment setting

### ISSUE THREAD

**Issue by QiuJYWX** [RiS3-Lab/FICS-#1]
Hi,
Thanks for your sharing of this repo. Would u please provide the version of the OS and python?

Regards,

**Comment by ManSoSec** [comment]
Hi,

I have tested the repo on Ubuntu 16 and python 2.7. It may work on higher versions of Ubuntu.

**Comment by QiuJYWX** [comment]
> Hi,
> 
> I have tested the repo on Ubuntu 16 and python 2.7. It may work on higher versions of Ubuntu.

Hi ManSoSec,
Thanks for your quickly reply. Will try to run this repo:)
