### ISSUE TITLE
No results has been found

### ISSUE THREAD

**Issue by QiuJYWX** [RiS3-Lab/FICS-#2]
Hi @ManSoSec ,

Thanks for your time and attention. I have run this repo successfully. However, no results has been detected. Would you please give me some advice?

_Running the code by 8 CPUs
=======================================
| Retrieve PDG from the LLVM bitcodes |
=======================================
Analyzing libtiff-19f6b70
No bitcode found
/home/qjy/.local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/qjy/Desktop/FICS
Running the code by 8 CPUs
=======================================
|   Extract Abstract Slices from PDG  |
=======================================
Analyzing libtiff-19f6b70
No pdg found
/home/qjy/.local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/qjy/Desktop/FICS
Running the code by 8 CPUs
=======================================
|          Extract features           |
=======================================
/home/qjy/.local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/qjy/Desktop/FICS
Running the code by 8 CPUs
=======================================
|          Extract features           |
=======================================
/home/qjy/.local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/qjy/Desktop/FICS
Running the code by 8 CPUs
=======================================
|            Cluster samples          |
=======================================
/home/qjy/.local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/qjy/Desktop/FICS
Running the code by 8 CPUs
=======================================
|            Cluster samples          |
=======================================

qjy@ubuntu:~/Desktop/FICS$ python __init__.py -a=QI -p=libtiff-19f6b70 -it=check -f
/home/qjy/.local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/home/qjy/Desktop/FICS
Running the code by 8 CPUs
=======================================
|        Query Inconsistencies         |
=======================================
Project: libtiff-19f6b70
Inconsistency Type: check
Total Number of reported inconsistencies: 0
Total Number of check inconsistencies (No filtering): 0
Total Number of inconsistencies after filtering: 0
Press Enter to show the inconsistencies..._

**Comment by QiuJYWX** [comment]
This may be caused by the inappropriate settings in the 'setting.py' file. Would you please give a complete filled version of 'setting.py' and provide some descriptions of the parameters if possible? 
Thanks and hope to receive your feedback.

**Comment by ManSoSec** [comment]
Please read the instructions in readme. You just need to change DATA_DIR in settings.py

**Comment by ManSoSec** [comment]
You also need to compile your target codebase:

https://github.com/RiS3-Lab/FICS/blob/main/README.md#prepare-target-codebase

**Comment by QiuJYWX** [comment]
> You also need to compile your target codebase:
> 
> https://github.com/RiS3-Lab/FICS/blob/main/README.md#prepare-target-codebase

Hi @ManSoSec ，
Thanks for your reply. I did have compiled the target codebase successfully and changed the DATA_DIR accordingly. However, no results have been detected.

roject: libtiff-19f6b70
Inconsistency Type: check
Total Number of reported inconsistencies: 0
Total Number of check inconsistencies (No filtering): 0
Total Number of inconsistencies after filtering: 0
Press Enter to show the inconsistencies..._

**Comment by QiuJYWX** [comment]
I have executed every step successfully without any errors according to readme.md

**Comment by ManSoSec** [comment]
Can you check if the bitcodes and graphs have been generated? They are in DATA_DIR directory.

Also check the status of mongodb: 
systemctl status mongod

**Comment by QiuJYWX** [comment]
Hi ManSoSec,
I have checked that the mongod service has been started successfully. However, The bitcodes and graphs has not been generated. In the DATA_DIR directory, only the 'bcs' folder has been generated, and one **llvm.log.txt** within it shows that 'clang: error: no such file or directory: ''check_tag.c '

**Comment by ManSoSec** [comment]
When you ran sh install.sh, are you sure everything were installed successfully?

Did you use "bear make" to compile the repo? If so, can you attach compile_commands.json?

**Comment by QiuJYWX** [comment]
Yes, I did install all the packages and bear make the _Libtiff_ projects successfully. The _compile_commands.json_ has also been generated ：（

**Comment by QiuJYWX** [comment]
> When you ran sh install.sh, are you sure everything were installed successfully?
> 
> Did you use "bear make" to compile the repo? If so, can you attach compile_commands.json?

Hi ManSoSec,

Thanks for your kindly help. I have executed this repo with the produced output results successfully on a new Ubuntu16.04 OS. During the running process, there are some errors, I am not sure it is caused by the incorrect settings or not, would you please give me some advice ?

_=======================================
|   Extract Abstract Slices from PDG  |
=======================================
Analyzing libtiff-19f6b70
 15%|███████████████████████████████████████▊                                                                                                                                                                                                                           | 165/1072 [00:14<00:44, 20.26it/s]Error: syntax error in line 54143 near 'Warning'
Error in reading:  /home/qjy/Desktop/FICS/data/bcs/libtiff-19f6b70/tools/tiffdump.c/pdg/dump.pdg.dot
Error: syntax error in line 55310 near 'Warning'
Error in reading:  /home/qjy/Desktop/FICS/data/bcs/libtiff-19f6b70/tools/tiffdump.c/pdg/main.pdg.dot
 18%|█████████████████████████████████████████████▋                                                                                                                                                                                                                     | 189/1072 [00:17<02:14,  6.56it/s]Error: syntax error in line 66769 near 'Warning'
Error in reading:  /home/qjy/Desktop/FICS/data/bcs/libtiff-19f6b70/tools/tiffcrop.c/pdg/main.pdg.dot
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 1070/1072 [03:05<00:07,  3.63s/it]


=======================================
|          Extract features           |
=======================================
Extracting afs.bb1_NN features for libtiff-19f6b70
  0%|                                                                                                                                                                                                                                                                           | 0/120566 [00:00<?, ?it/s]No chunk is available
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120566/120566 [01:33<00:00, 2031.11it/s]_

**Comment by ManSoSec** [comment]
The problem is the bitcodes and graphs are not generated successfully. There should be a problem when the code uses clang to extract bitcodes. Not exactly sure why this happens for you.

Can you do two more experiments? Can you check another codebase and see if the problem is still present? Second, can you try on a fresh Ubuntu?

**Comment by QiuJYWX** [comment]
> The problem is the bitcodes and graphs are not generated successfully. There should be a problem when the code uses clang to extract bitcodes. Not exactly sure why this happens for you.
> 
> Can you do two more experiments? Can you check another codebase and see if the problem is still present? Second, can you try on a fresh Ubuntu?

Hi @ManSoSec,
Thanks for your suggestion. Will try to re-run the project on a fresh Ubuntu. 
BTW, would u please provide us the download links (especially the detailed versions) and the corresponding compile methods of the other codebases. We have downloaded 2 codebases (https://github.com/wolfSSL/wolfssl, https://github.com/LibreDWG/libredwg) but cannot compile them successfully using the cmake-clang method provided in '_readme.md_'.

**Comment by ManSoSec** [comment]
Please refer to the web page of each project for the compile instructions. Or you can find the build commands of many Codebase here:

https://github.com/google/oss-fuzz/tree/master/projects

**Comment by QiuJYWX** [comment]
> Please refer to the web page of each project for the compile instructions. Or you can find the build commands of many Codebase here:
> 
> https://github.com/google/oss-fuzz/tree/master/projects

Hi @ManSoSec ,
Thanks for your reply. Will try it accordingly.

Regards,
