### ISSUE TITLE
---------------------

### ISSUE THREAD

**Issue by hwphappy** [RiS3-Lab/FICS-#7]
编译仅仅支持clang3.8；支持这个版本的ubuntu最高版本为16.04；
里面的python代码，使用的是python2编写的，这些都没怎么提及；
坑已经踩过啦，希望后来的兄弟，多多注意！

**Comment by wuts0301** [comment]
兄弟，你复现成功了吗？我遇到点问题，看见了可以交流一下哈。wuts0301@163.com

**Comment by wuts0301** [comment]
> 编译仅仅支持clang3.8；支持这个版本的ubuntu最高版本为16.04； 里面的python代码，使用的是python2编写的，这些都没怎么提及； 坑已经踩过啦，希望后来的兄弟，多多注意！

**Comment by wuts0301** [comment]
> 编译仅仅支持clang3.8；支持这个版本的ubuntu最高版本为16.04； 里面的python代码，使用的是python2编写的，这些都没怎么提及； 坑已经踩过啦，希望后来的兄弟，多多注意！

**Comment by wuts0301** [comment]
@hwphappy  兄弟，你复现成功了吗？我复现遇到点问题想请教一下，卡在“Extract Abstract Slices from PDG”这一步。方便的话wuts0301@163.com

**Comment by hwphappy** [comment]
https://hwpno1.blog.csdn.net/article/details/120126806

**Comment by hwphappy** [comment]
> @hwphappy 兄弟，你复现成功了吗？我复现遇到点问题想请教一下，卡在“Extract Abstract Slices from PDG”这一步。方便的话[wuts0301@163.com](mailto:wuts0301@163.com)

意义不大了吧

**Comment by wuts0301** [comment]
> > @hwphappy 兄弟，你复现成功了吗？我复现遇到点问题想请教一下，卡在“Extract Abstract Slices from PDG”这一步。方便的话[wuts0301@163.com](mailto:wuts0301@163.com)
> 
> 意义不大了吧

额，为什么这么说呢，这个研究点意义不大了吗？

**Comment by hwphappy** [comment]
> > > @hwphappy 兄弟，你复现成功了吗？我复现遇到点问题想请教一下，卡在“Extract Abstract Slices from PDG”这一步。方便的话[wuts0301@163.com](mailto:wuts0301@163.com)
> > 
> > 
> > 意义不大了吧
> 
> 额，为什么这么说呢，这个研究点意义不大了吗？

抱歉，那一段。非客观因素。导致说话不太严谨。
我尝试做了跑通，但是；可能因为没有数据集的原因，最终也没成功；
不过，即使跑不通；也可以试着去理解一下原作者的构造思路；学习一下思想。

**Comment by wuts0301** [comment]
> > > > @hwphappy 兄弟，你复现成功了吗？我复现遇到点问题想请教一下，卡在“Extract Abstract Slices from PDG”这一步。方便的话[wuts0301@163.com](mailto:wuts0301@163.com)
> > > 
> > > 
> > > 意义不大了吧
> > 
> > 
> > 额，为什么这么说呢，这个研究点意义不大了吗？
> 
> 抱歉，那一段。非客观因素。导致说话不太严谨。 我尝试做了跑通，但是；可能因为没有数据集的原因，最终也没成功； 不过，即使跑不通；也可以试着去理解一下原作者的构造思路；学习一下思想。

好的，谢谢~！

**Comment by 99hansling** [comment]
> 编译仅仅支持clang3.8；支持这个版本的ubuntu最高版本为16.04； 里面的python代码，使用的是python2编写的，这些都没怎么提及； 坑已经踩过啦，希望后来的兄弟，多多注意！

兄弟，我这边也在看。然后我这边提供给我的云是ubuntu 20 版本的，还有办法通过引入新的源来引入clang-3.8吗？查了好久都不行欸

**Comment by yyoumaa** [comment]
才看到原来只有16.04可以。。。但为什么我用18也装上了3.8还跑起来了呢，只不过后面几步卡住了
